//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SiparisTakipSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiparisTakipEntities : DbContext
    {
        public SiparisTakipEntities()
            : base("name=SiparisTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonelikler> Aboneliklers { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Magaza> Magazas { get; set; }
        public virtual DbSet<Mesaj> Mesajs { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<Uretici> Ureticis { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    
        public virtual ObjectResult<SP_SiparisDurumları_Result> SP_SiparisDurumları()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SiparisDurumları_Result>("SP_SiparisDurumları");
        }
    
        public virtual ObjectResult<SP_SiparisDurumlarıJoin_Result> SP_SiparisDurumlarıJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SiparisDurumlarıJoin_Result>("SP_SiparisDurumlarıJoin");
        }
    
        public virtual ObjectResult<SP_UrunlerJoin_Result> SP_UrunlerJoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UrunlerJoin_Result>("SP_UrunlerJoin");
        }
    }
}
